---
- hosts: localhost
  connection: local
  become: false
  gather_facts: true
  vars:
    quay_root: "/opt/quay"
    quay_hostname: "quay"
    quay_port: 8443
    launched_by_systemd: false

  tasks:

    - name: Include tasks to replace quay certificates
      include_tasks:
        name: replace-certificates.yml
