---
  # Only when running outside of systemd
- name: Stop Quay services
  systemd:
    name: "{{ item }}"
    state: stopped
  loop:
    - "quay-app.service"
    - "quay-redis.service"
    - "quay-postgres.service"
    - "quay-app.service"
  loop_control:
    pause: 5
  when:
    - not (launched_by_systemd | bool)

- name: Get hostname
  command: hostname
  register: hostname_info

- name: Set hostname fact
  set_fact:
    my_hostname: "{{ hostname_info.stdout }}"

- name: Change SERVER_HOSTNAME in quay config to current hostname
  ansible.builtin.lineinfile:
    path: "{{ quay_root }}/quay-config/config.yaml"
    regexp: '^SERVER_HOSTNAME:.*'
    line: "SERVER_HOSTNAME: {{ my_hostname }}:{{ quay_port }}"

- name: Remove existing certs
  file:
    path: "{{ item }}"
    state: absent
  loop:
    - "{{ quay_root }}/quay-config/openssl.cnf"
    - "{{ quay_root }}/quay-config/ssl.cert"
    - "{{ quay_root }}/quay-config/ssl.csr"
    - "{{ quay_root }}/quay-config/ssl.key"
    - "{{ quay_root }}/quay-rootCA/rootCA.pem"
    - "{{ quay_root }}/quay-rootCA/rootCA.srl"
    - "{{ quay_root }}/quay-rootCA/rootCA.key"
  
- name: Create SSL Certs
  block:
    - name: Create necessary directory for Quay rootCA files
      ansible.builtin.file:
        path: "{{ quay_root }}/quay-rootCA"
        state: directory
        recurse: yes
        
    - name: Create OpenSSL Config
      template:
        src: templates/req.j2
        dest: "{{ quay_root }}/quay-config/openssl.cnf"

    - name: Create root CA key
      command: "openssl genrsa -out {{ quay_root }}/quay-rootCA/rootCA.key 2048"

    - name: Create root CA pem
      command: "openssl req -x509 -new -config {{ quay_root }}/quay-config/openssl.cnf -nodes -key {{ quay_root }}/quay-rootCA/rootCA.key -sha256 -days 1024 -out {{ quay_root }}/quay-rootCA/rootCA.pem -addext basicConstraints=critical,CA:TRUE,pathlen:1"

    - name: Create ssl key
      command: "openssl genrsa -out {{ quay_root }}/quay-config/ssl.key 2048"

    - name: Create CSR
      command: "openssl req -new -key {{ quay_root }}/quay-config/ssl.key -out {{ quay_root }}/quay-config/ssl.csr -subj \"/CN=quay-enterprise\" -config {{ quay_root }}/quay-config/openssl.cnf"

    - name: Create self-signed cert
      command: "openssl x509 -req -in {{ quay_root }}/quay-config/ssl.csr -CA {{ quay_root }}/quay-rootCA/rootCA.pem -CAkey {{ quay_root }}/quay-rootCA/rootCA.key -CAcreateserial -out {{ quay_root }}/quay-config/ssl.cert -days 356 -extensions v3_req -extfile {{ quay_root }}/quay-config/openssl.cnf"

    - name: Create chain cert
      ansible.builtin.shell: cat {{ quay_root }}/quay-config/ssl.cert {{ quay_root }}/quay-rootCA/rootCA.pem > {{ quay_root }}/quay-config/chain.cert

    - name: Replace ssl cert with chain cert
      command: mv --force {{ quay_root }}/quay-config/chain.cert {{ quay_root }}/quay-config/ssl.cert

- name: Set certificate permissions
  block:
    - name: Set permissions for key
      ansible.builtin.file:
        path: "{{ quay_root }}/quay-config/ssl.key"
        mode: u=rw,g=r,o=r
        owner: root
        group: root

    - name: Set permissions for cert
      ansible.builtin.file:
        path: "{{ quay_root }}/quay-config/ssl.cert"
        mode: u=rw,g=r,o=r
        owner: root
        group: root

- name: Remove existing certificate copies
  file:
    path: '{{ item }}'
    state: absent
  with_items:
    - '/etc/pki/ca-trust/source/anchors/quay.cert"'

# Make sure to trust the self signed cert we just made
- name: Copy self signed cert to registry's PKI trust
  become: true
  copy:
    src: "{{ quay_root }}/quay-config/ssl.cert"
    dest: '/etc/pki/ca-trust/source/anchors/quay.cert'
    remote_src: true

- name: update registry trusted ca
  command: update-ca-trust

- name: update registry trusted ca extract
  command: update-ca-trust extract

  # Only when running outside of systemd
- name: Start Quay services
  systemd:
    name: "{{ item }}"
    state: started
  loop:
    - "quay-pod.service"
    - "quay-postgres.service"
    - "quay-redis.service"
    - "quay-app.service"
  loop_control:
    pause: 5
  when:
    - not (launched_by_systemd | bool)

  # Stop systemd from running this playbook
  # There is no check at the top for this so users can run
  # the playbook manually
- name: Touch firstboot file
  ansible.builtin.file:
    path: /etc/sysconfig/rh-quay-firstboot
    state: touch
