apiVersion: mirror.openshift.io/v1alpha2
kind: ImageSetConfiguration
storageConfig:
  registry:
    imageURL: localhost:8443/oc-mirror-state:latest # Stores metadata in an image
    skipTLS: true
mirror:
  platform:
    channels:
      - name: stable-OCP_MAJ_VER
        minVersion: OCP_MIN_VER
        maxVersion: OCP_MAX_VER
    graph: true # Include Cincinnati upgrade graph image in imageset
  operators:
    - catalog: registry.redhat.io/redhat/redhat-operator-index:vOCP_MAJ_VER
      packages:
        - name: advanced-cluster-management
          channels:
            - name: advanced-cluster-management-CHANNEL
              minVersion: advanced-cluster-management-VERSION
        - name: ansible-automation-platform-operator
          channels:
            - name: ansible-automation-platform-operator-CHANNEL
              minVersion: ansible-automation-platform-operator-VERSION
        - name: cincinnati-operator
          channels:
            - name: cincinnati-operator-CHANNEL
              minVersion: cincinnati-operator-VERSION
        - name: cluster-logging
          channels:
            - name: cluster-logging-CHANNEL
              minVersion: cluster-logging-VERSION
        - name: compliance-operator
          channels:
            - name: compliance-operator-CHANNEL
              minVersion: compliance-operator-VERSION
        - name: elasticsearch-operator
          channels:
            - name: elasticsearch-operator-CHANNEL
              minVersion: elasticsearch-operator-VERSION
        - name: file-integrity-operator
          channels:
            - name: file-integrity-operator-CHANNEL
              minVersion: file-integrity-operator-VERSION
        - name: mcg-operator
          channels:
            - name: mcg-operator-CHANNEL
              minVersion: mcg-operator-VERSION
        - name: nfd
          channels:
            - name: nfd-CHANNEL
              minVersion: nfd-VERSION
        - name: rhacs-operator
          channels:
            - name: rhacs-operator-CHANNEL
              minVersion: rhacs-operator-VERSION
        - name: rhsso-operator
          channels:
            - name: rhsso-operator-CHANNEL
              minVersion: rhsso-operator-VERSION
        - name: costmanagement-metrics-operator
          channels:
            - name: costmanagement-metrics-operator-CHANNEL
              minVersion: costmanagement-metrics-operator-VERSION
        - name: mtc-operator
          channels:
            - name: mtc-operator-CHANNEL
              minVersion: mtc-operator-VERSION
        - name: mtv-operator
          channels:
            - name: mtv-operator-CHANNEL
              minVersion: mtv-operator-VERSION
        - name: multicluster-engine
          channels:
            - name: multicluster-engine-CHANNEL
              minVersion: multicluster-engine-VERSION
        - name: node-healthcheck-operator
          channels:
            - name: node-healthcheck-operator-CHANNEL
              minVersion: node-healthcheck-operator-VERSION
        - name: node-maintenance-operator
          channels:
            - name: node-maintenance-operator-CHANNEL
              minVersion: node-maintenance-operator-VERSION
        - name: numaresources-operator
          channels:
            - name: "numaresources-operator-CHANNEL"
              minVersion: numaresources-operator-VERSION
        - name: odf-multicluster-orchestrator
          channels:
            - name: odf-multicluster-orchestrator-CHANNEL
              minVersion: odf-multicluster-orchestrator-VERSION
        - name: odr-cluster-operator
          channels:
            - name: odr-cluster-operator-CHANNEL
              minVersion: odr-cluster-operator-VERSION
        - name: odr-hub-operator
          channels:
            - name: odr-hub-operator-CHANNEL
              minVersion: odr-hub-operator-VERSION
        - name: openshift-cert-manager-operator
          channels:
            - name: openshift-cert-manager-operator-CHANNEL
              minVersion: openshift-cert-manager-operator-VERSION
        - name: openshift-custom-metrics-autoscaler-operator
          channels:
            - name: openshift-custom-metrics-autoscaler-operator-CHANNEL
              minVersion: openshift-custom-metrics-autoscaler-operator-VERSION
        - name: openshift-gitops-operator
          channels:
            - name: openshift-gitops-operator-CHANNEL
              minVersion: openshift-gitops-operator-VERSION
        - name: openshift-pipelines-operator-rh
          channels:
            - name: openshift-pipelines-operator-rh-CHANNEL
              minVersion: openshift-pipelines-operator-rh-VERSION
        - name: openshift-secondary-scheduler-operator
          channels:
            - name: openshift-secondary-scheduler-operator-CHANNEL
              minVersion: openshift-secondary-scheduler-operator-VERSION
        - name: openshift-special-resource-operator
          channels:
            - name: openshift-special-resource-operator-CHANNEL
              minVersion: openshift-special-resource-operator-VERSION
        - name: quay-bridge-operator
          channels:
            - name: quay-bridge-operator-CHANNEL
              minVersion: quay-bridge-operator-VERSION
        - name: quay-operator
          channels:
            - name: quay-operator-CHANNEL
              minVersion: quay-operator-VERSION
        - name: redhat-oadp-operator
          channels:
            - name: redhat-oadp-operator-CHANNEL
              minVersion: redhat-oadp-operator-VERSION
        - name: rh-service-binding-operator
          channels:
            - name: rh-service-binding-operator-CHANNEL
              minVersion: rh-service-binding-operator-VERSION
        - name: serverless-operator
          channels:
            - name: serverless-operator-CHANNEL
              minVersion: serverless-operator-VERSION
  additionalimages:
    - name: registry.access.redhat.com/ubi8/ubi-micro
    - name: registry.access.redhat.com/ubi8/ubi-minimal
    - name: registry.access.redhat.com/ubi8/ubi-init
    - name: registry.access.redhat.com/ubi8/s2i-core
    - name: registry.access.redhat.com/ubi8/s2i-base
    - name: registry.access.redhat.com/ubi8/pause
    - name: registry.access.redhat.com/ubi9/ubi-micro
    - name: registry.access.redhat.com/ubi9/ubi-minimal
    - name: registry.access.redhat.com/ubi9/ubi-init
    - name: registry.access.redhat.com/ubi9/s2i-core
    - name: registry.access.redhat.com/ubi9/s2i-base
    - name: registry.access.redhat.com/ubi9/pause
