---
- hosts: localhost
  become: false
  gather_facts: true

  tasks:

    - name: Include tasks to replace quay certificates
      ansible.builtin.include_tasks: tasks/replace-certificates.yml

    - name: Include tasks to update oc mirror metadata files
      ansible.builtin.include_tasks: tasks/update-metadata-files.yml
